/*
 * DO NOT EDIT!
 * 
 * Automatically generated source code by Pitch Developer Studio
 * Licensed to Hridyanshu Aatreya, Pitch UK P, Project Edition
 *
 * Copyright (C) 2006-2024 Pitch Technologies AB. All rights reserved.
 * Use is subject to license terms.
 */

/**
 * Main package for the API generated by Pitch Developer Studio.
 * <p>
 * Start by creating an instance of the {@link uk.ac.brunel.see.HlaWorld} interface by calling
 * {@link uk.ac.brunel.see.HlaWorld.Factory#create HlaWorld.Factory.create()}.
 */
package uk.ac.brunel.see;
